import React, { useState, useEffect } from 'react';
import { useParams, useLocation, useNavigate } from 'react-router-dom';
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer,
         BarChart, Bar, XAxis, YAxis, Tooltip, Cell } from 'recharts';

const API  = process.env.REACT_APP_API_URL || 'https://pragati-backend-ixn3.onrender.com/api';
const tk   = () => ({ Authorization: `Bearer ${localStorage.getItem('pragati_token')}` });
const GRAD = 'linear-gradient(135deg,#531697,#13a1a5)';

function ScoreRing({ score, label, color, size = 90 }) {
  const r    = (size / 2) - 10;
  const circ = 2 * Math.PI * r;
  const offset = circ - (score / 100) * circ;
  return (
    <div style={{ textAlign: 'center' }}>
      <svg width={size} height={size} style={{ transform: 'rotate(-90deg)' }}>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#f0f3fa" strokeWidth={8} />
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth={8}
          strokeDasharray={`${circ}`} strokeDashoffset={offset} strokeLinecap="round"
          style={{ transition: 'stroke-dashoffset 1.2s ease' }} />
      </svg>
      <div style={{ marginTop: -size/2-4, fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize: size>80?'1.3rem':'.9rem', color:'#0f1a2e' }}>{score}</div>
      <div style={{ marginTop: size/2-8, fontSize:'.68rem', fontWeight:700, color:'#7a8ba8', textTransform:'uppercase', letterSpacing:'0.05em' }}>{label}</div>
    </div>
  );
}

const SCORE_COLORS = {
  communication: '#531697', confidence: '#13a1a5', leadership: '#f59e0b',
  participation: '#47d372', fluency: '#3b82f6', relevance: '#ec4899', teamwork: '#8b5cf6',
};

// ── AI Summary Card — redesigned professional layout ─────────────────────────
function AISummaryCard({ scores }) {
  const readinessColor = { 'Ready':'#22c55e','Near Ready':'#f59e0b','Needs Practice':'#ef4444' }[scores.placementReadiness]||'#7a8ba8';
  const readinessIcon  = { 'Ready':'✅','Near Ready':'🔶','Needs Practice':'📈' }[scores.placementReadiness]||'🤖';

  return (
    <div style={{ marginBottom:14 }}>
      {/* Card header */}
      <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:16 }}>
        <div style={{ width:38, height:38, borderRadius:10, background:'linear-gradient(135deg,#531697,#13a1a5)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'1.1rem', flexShrink:0 }}>
          🤖
        </div>
        <div>
          <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'1rem', color:'#0f1a2e' }}>AI Performance Summary</div>
          <div style={{ fontSize:'.72rem', color:'#7a8ba8', fontWeight:600 }}>Generated by PRAGATI AI Evaluator</div>
        </div>
        {scores.placementReadiness && (
          <div style={{ marginLeft:'auto', display:'inline-flex', alignItems:'center', gap:5, padding:'5px 14px', borderRadius:20, background:`${readinessColor}15`, border:`1.5px solid ${readinessColor}`, color:readinessColor, fontWeight:800, fontSize:'.78rem', whiteSpace:'nowrap' }}>
            {readinessIcon} {scores.placementReadiness}
          </div>
        )}
      </div>

      {/* Summary box */}
      {scores.summary && (
        <div style={{ marginBottom:12, borderRadius:12, overflow:'hidden', border:'1px solid rgba(83,22,151,0.15)' }}>
          <div style={{ padding:'9px 14px', background:'linear-gradient(90deg,rgba(83,22,151,0.1),rgba(19,161,165,0.06))', display:'flex', alignItems:'center', gap:8, borderBottom:'1px solid rgba(83,22,151,0.1)' }}>
            <span style={{ fontSize:'.9rem' }}>📋</span>
            <span style={{ fontSize:'.7rem', fontWeight:800, color:'#531697', textTransform:'uppercase', letterSpacing:'0.07em' }}>Behavioural Summary</span>
          </div>
          <div style={{ padding:'14px 16px', background:'rgba(83,22,151,0.03)' }}>
            <p style={{ margin:0, fontSize:'.87rem', color:'#3d4e6b', lineHeight:1.75, fontStyle:'italic' }}>
              "{scores.summary}"
            </p>
          </div>
        </div>
      )}

      {/* Detailed feedback box */}
      {scores.detailedFeedback && (
        <div style={{ borderRadius:12, overflow:'hidden', border:'1px solid rgba(19,161,165,0.18)' }}>
          <div style={{ padding:'9px 14px', background:'linear-gradient(90deg,rgba(19,161,165,0.1),rgba(83,22,151,0.05))', display:'flex', alignItems:'center', gap:8, borderBottom:'1px solid rgba(19,161,165,0.12)' }}>
            <span style={{ fontSize:'.9rem' }}>🔍</span>
            <span style={{ fontSize:'.7rem', fontWeight:800, color:'#13a1a5', textTransform:'uppercase', letterSpacing:'0.07em' }}>Detailed Analysis</span>
          </div>
          <div style={{ padding:'14px 16px', background:'rgba(19,161,165,0.03)' }}>
            {/* Split into sentences for a cleaner reading experience */}
            {scores.detailedFeedback.split('. ').filter(Boolean).map((sentence, i) => (
              <div key={i} style={{ display:'flex', gap:10, marginBottom:8, alignItems:'flex-start' }}>
                <div style={{ width:6, height:6, borderRadius:'50%', background:'linear-gradient(135deg,#531697,#13a1a5)', flexShrink:0, marginTop:8 }} />
                <p style={{ margin:0, fontSize:'.85rem', color:'#3d4e6b', lineHeight:1.7 }}>
                  {sentence.trim()}{sentence.trim().endsWith('.')?'':'.'}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function GDReportPage() {
  const { code, userId } = useParams();
  const location = useLocation();
  const nav      = useNavigate();
  const [data,    setData]    = useState(null);
  const [loading, setLoading] = useState(true);

  const isPartial = location.state?.isPartial || false;

  useEffect(() => {
    const passedEval = location.state?.evalData;
    if (passedEval) {
      const me = passedEval.participants?.find(p => p.userId === userId || p.userId?.toString() === userId);
      if (me) {
        setData({ participant: me, topic: location.state?.topic, roomCode: code, myStats: location.state?.myStats });
        setLoading(false); return;
      }
    }
    fetch(`${API}/gd/rooms/${code}/report/${userId}`, { headers: tk() })
      .then(r => r.json()).then(d => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, [code, userId, location.state]);

  if (loading) return (
    <div style={{ display:'flex', justifyContent:'center', alignItems:'center', minHeight:'50vh', flexDirection:'column', gap:12 }}>
      <div style={{ width:40, height:40, border:'3px solid #e8edf5', borderTopColor:'#531697', borderRadius:'50%', animation:'_s .7s linear infinite' }} />
      <style>{`@keyframes _s{to{transform:rotate(360deg)}}`}</style>
      <div style={{ color:'#b0bec9' }}>Generating AI evaluation…</div>
    </div>
  );

  if (!data?.participant) return (
    <div style={{ textAlign:'center', padding:60 }}>
      <div style={{ fontSize:'2rem', marginBottom:12 }}>📋</div>
      <div style={{ color:'#7a8ba8' }}>Report not available yet. Please wait for evaluation to complete.</div>
      <button onClick={() => nav('/dashboard/gd')} style={{ marginTop:16, padding:'9px 20px', borderRadius:10, border:'none', background:GRAD, color:'#fff', fontWeight:800, cursor:'pointer', fontFamily:"'Nunito',sans-serif" }}>← Back to Lobby</button>
    </div>
  );

  const { participant, topic, myStats } = data;
  const scores       = participant.aiScore || {};
  const overall      = scores.overall || 0;
  const overallColor = overall>=75?'#22c55e':overall>=55?'#f59e0b':'#ef4444';
  const overallLabel = overall>=75?'🌟 Excellent — Ready for Placement GD!':overall>=55?'👍 Good — Minor improvements needed':'📈 Developing — Practice more GDs';

  const radarData = [
    { subject:'Communication', score: scores.communication||0 },
    { subject:'Confidence',    score: scores.confidence   ||0 },
    { subject:'Leadership',    score: scores.leadership   ||0 },
    { subject:'Participation', score: scores.participation||0 },
    { subject:'Fluency',       score: scores.fluency      ||0 },
    { subject:'Relevance',     score: scores.relevance    ||0 },
    { subject:'Teamwork',      score: scores.teamwork     ||0 },
  ];

  const barData = Object.entries(SCORE_COLORS).map(([key, color]) => ({
    name: key.charAt(0).toUpperCase()+key.slice(1),
    score: scores[key]||0,
    color,
  }));

  return (
    <div style={{ fontFamily:"'Nunito',sans-serif", maxWidth:960, margin:'0 auto', padding:'0 8px 40px' }}>

      {/* Partial session banner */}
      {isPartial && (
        <div style={{ margin:'16px 0', padding:'12px 18px', borderRadius:10, background:'rgba(245,158,11,0.1)', border:'1.5px solid rgba(245,158,11,0.35)', display:'flex', alignItems:'center', gap:10 }}>
          <span style={{ fontSize:'1.2rem' }}>⚡</span>
          <div>
            <div style={{ fontWeight:800, fontSize:'.88rem', color:'#b45309' }}>Partial Session Report</div>
            <div style={{ fontSize:'.78rem', color:'#92400e' }}>You left before the session ended. This report is based on your participation so far.</div>
          </div>
        </div>
      )}

      {/* Header */}
      <div style={{ background:GRAD, borderRadius:16, padding:'28px 32px', marginBottom:20, color:'#fff' }}>
        <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'1.5rem', marginBottom:6 }}>
          📊 AI Evaluation Report
        </div>
        <div style={{ opacity:.85, fontSize:'.88rem', marginBottom:4 }}>Participant: <strong>{participant.name}</strong></div>
        {topic && <div style={{ opacity:.75, fontSize:'.8rem' }}>Topic: "{topic}"</div>}
        {isPartial && <div style={{ marginTop:8, display:'inline-block', padding:'3px 12px', borderRadius:20, background:'rgba(255,255,255,0.2)', fontSize:'.72rem', fontWeight:700 }}>⚡ Partial Session</div>}
      </div>

      {/* Overall score + readiness */}
      <div className="card" style={{ padding:'28px 32px', marginBottom:16, textAlign:'center' }}>
        <div style={{ marginBottom:8 }}>
          <span style={{ fontSize:'3.5rem', fontFamily:"'Syne',sans-serif", fontWeight:800, color:overallColor }}>{overall}</span>
          <span style={{ fontSize:'1.5rem', color:'#b0bec9' }}>/100</span>
        </div>
        <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'1.1rem', color:'#0f1a2e', marginBottom:10 }}>{overallLabel}</div>
        <div style={{ display:'flex', flexWrap:'wrap', justifyContent:'center', gap:20, marginTop:10 }}>
          {Object.entries(SCORE_COLORS).map(([key, color]) => (
            <ScoreRing key={key} score={scores[key]||0} label={key} color={color} size={82} />
          ))}
        </div>
      </div>

      {/* Charts row */}
      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14, marginBottom:14 }}>
        <div className="card" style={{ padding:'20px 16px' }}>
          <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'.9rem', marginBottom:12 }}>📡 Skill Radar</div>
          <ResponsiveContainer width="100%" height={220}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="#e8edf5" />
              <PolarAngleAxis dataKey="subject" tick={{ fontSize:10, fill:'#7a8ba8', fontFamily:"'Nunito',sans-serif" }} />
              <Radar name="Score" dataKey="score" stroke="#531697" fill="#531697" fillOpacity={0.18} strokeWidth={2} />
            </RadarChart>
          </ResponsiveContainer>
        </div>
        <div className="card" style={{ padding:'20px 16px' }}>
          <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'.9rem', marginBottom:12 }}>📊 Dimension Scores</div>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={barData} layout="vertical" margin={{ left:20 }}>
              <XAxis type="number" domain={[0,100]} tick={{ fontSize:10 }} />
              <YAxis type="category" dataKey="name" tick={{ fontSize:10, fontFamily:"'Nunito',sans-serif" }} width={90} />
              <Tooltip formatter={(v) => [`${v}/100`]} />
              <Bar dataKey="score" radius={4}>
                {barData.map((entry,i) => <Cell key={i} fill={entry.color} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* ── AI Summary — redesigned ── */}
      {(scores.summary || scores.detailedFeedback) && (
        <div className="card" style={{ padding:'22px 24px', marginBottom:14 }}>
          <AISummaryCard scores={scores} />
        </div>
      )}

      {/* Strengths + Improvements */}
      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14, marginBottom:14 }}>
        {scores.strengths?.length>0 && (
          <div className="card" style={{ padding:'18px 20px' }}>
            <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'.9rem', color:'#22c55e', marginBottom:14, display:'flex', alignItems:'center', gap:6 }}>
              <span style={{ width:28, height:28, borderRadius:8, background:'rgba(34,197,94,0.12)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'.9rem' }}>✅</span>
              Strengths
            </div>
            {scores.strengths.map((s,i) => (
              <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'8px 0', borderBottom:i<scores.strengths.length-1?'1px solid #f0f3fa':'none' }}>
                <div style={{ width:20, height:20, borderRadius:6, background:'rgba(34,197,94,0.12)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0, marginTop:1 }}>
                  <div style={{ width:6, height:6, borderRadius:'50%', background:'#22c55e' }} />
                </div>
                <span style={{ fontSize:'.83rem', color:'#3d4e6b', lineHeight:1.55 }}>{s}</span>
              </div>
            ))}
          </div>
        )}
        {scores.improvements?.length>0 && (
          <div className="card" style={{ padding:'18px 20px' }}>
            <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'.9rem', color:'#f59e0b', marginBottom:14, display:'flex', alignItems:'center', gap:6 }}>
              <span style={{ width:28, height:28, borderRadius:8, background:'rgba(245,158,11,0.12)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'.9rem' }}>🔧</span>
              Areas to Improve
            </div>
            {scores.improvements.map((imp,i) => (
              <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'8px 0', borderBottom:i<scores.improvements.length-1?'1px solid #f0f3fa':'none' }}>
                <div style={{ width:20, height:20, borderRadius:6, background:'rgba(245,158,11,0.12)', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0, marginTop:1 }}>
                  <div style={{ width:6, height:6, borderRadius:'50%', background:'#f59e0b' }} />
                </div>
                <span style={{ fontSize:'.83rem', color:'#3d4e6b', lineHeight:1.55 }}>{imp}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Speaking metrics */}
      {(myStats||participant) && (
        <div className="card" style={{ padding:'18px 24px', marginBottom:20 }}>
          <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'.9rem', marginBottom:14 }}>📈 Speaking Metrics</div>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:10 }}>
            {[
              ['🗣️','Speaking Time',`${participant.speakingTime||0}s`,'#531697'],
              ['💬','Words Spoken', participant.wordCount    ||0,   '#13a1a5'],
              ['⚠️','Filler Words', participant.fillerWords  ||0,   '#f59e0b'],
              ['🔔','Interruptions',participant.interruptions||0,   '#ef4444'],
            ].map(([ic,label,val,color]) => (
              <div key={label} style={{ textAlign:'center', padding:'14px 8px', borderRadius:12, background:'#f8faff', border:'1px solid #eef1f8' }}>
                <div style={{ fontSize:'1.4rem', marginBottom:5 }}>{ic}</div>
                <div style={{ fontFamily:"'Syne',sans-serif", fontWeight:800, fontSize:'1.2rem', color }}>{val}</div>
                <div style={{ fontSize:'.68rem', color:'#b0bec9', fontWeight:700, marginTop:2 }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      <div style={{ display:'flex', gap:12, justifyContent:'center' }}>
        <button onClick={() => nav('/dashboard/gd')} style={{ padding:'12px 28px', borderRadius:12, border:'none', background:GRAD, color:'#fff', fontWeight:800, cursor:'pointer', fontFamily:"'Nunito',sans-serif", fontSize:'1rem' }}>
          ← Back to Lobby
        </button>
        <button onClick={() => window.print()} style={{ padding:'12px 28px', borderRadius:12, border:'1.5px solid #d0d7e8', background:'transparent', color:'#3d4e6b', fontWeight:700, cursor:'pointer', fontFamily:"'Nunito',sans-serif" }}>
          🖨️ Print Report
        </button>
      </div>
    </div>
  );
}
